import type {
  ConnectionCapabilityLabel,
  ConnectionEntry,
  ConnectionGroup,
  ConnectionState,
} from "./types";
import type { YziImobRole } from "@/components/yzi-imob/yzi-imob-status-colors";

export const CONNECTION_GROUPS: ConnectionGroup[] = [
  {
    id: "meta",
    label: "Meta",
    description: "Conexão técnica única com os assets do ecossistema Meta.",
  },
  {
    id: "presenca-digital",
    label: "Presença digital",
    description: "Capacidades orgânicas e institucionais dos canais da imobiliária.",
  },
  {
    id: "anuncios",
    label: "Anúncios",
    description: "Contas, leitura, escrita e operação de campanhas pagas.",
  },
  {
    id: "producao-criativa",
    label: "Produção criativa",
    description: "Base de marca, templates, mídias e geração criativa.",
  },
];

export const CONNECTION_CAPABILITY_LABEL: ConnectionCapabilityLabel = {
  identified: "Conta identificada",
  read: "Leitura disponível",
  write: "Criação e edição",
  publish: "Publicação",
  metrics: "Métricas",
  "receber-contatos": "Receber contatos",
  "responder-mensagens": "Responder mensagens",
  "publicar-conteudo": "Publicar conteúdo",
  "programar-publicacao": "Programar publicação",
  "criar-anuncios": "Criar anúncios",
  "acompanhar-campanhas": "Acompanhar campanhas",
  "ler-metricas": "Ler métricas",
  "sincronizar-imoveis": "Sincronizar imóveis",
  "atualizar-informacoes": "Atualizar informações",
  "produzir-criativos": "Produzir criativos",
  "gerar-narracao": "Gerar narração",
};

export const CONNECTION_STATE_LABEL: Record<ConnectionState, string> = {
  conectado: "Conectado",
  "parcialmente-conectado": "Parcialmente conectado",
  "em-configuracao": "Em configuração",
  "aguardando-autorizacao": "Aguardando autorização",
  "nao-configurado": "Não configurado",
  "requer-atencao": "Requer atenção",
  "em-breve": "Disponível em breve",
};

export const CONNECTION_STATE_ROLE: Record<ConnectionState, YziImobRole> = {
  conectado: "coldGreen",
  "parcialmente-conectado": "amber",
  "em-configuracao": "amber",
  "aguardando-autorizacao": "amber",
  "nao-configurado": "neutral",
  "requer-atencao": "wine",
  "em-breve": "lilac",
};

export const CONNECTIONS_CATALOG: ConnectionEntry[] = [
  {
    id: "meta",
    groupId: "meta",
    label: "Meta",
    summary: "Conexão do WhatsApp Cloud API para atendimento, mensagens e estados.",
    state: "nao-configurado",
    priority: "essencial",
    capabilities: [],
    channels: [
      {
        id: "whatsapp",
        label: "WhatsApp",
        summary: "Canal de atendimento oficial da operação.",
        state: "nao-configurado",
        capabilities: [
          { id: "receber-contatos", unlocked: false },
          { id: "responder-mensagens", unlocked: false },
        ],
      },
    ],
    primaryPendency: "Configurar o WhatsApp Cloud API durante a implantação.",
    impact: ["Sem o WhatsApp configurado, o atendimento oficial permanece indisponível."],
    evidence: "produto",
    evidenceNote: "No MVP, a Meta é usada somente pelo WhatsApp Cloud API.",
  },
  {
    id: "metricool",
    groupId: "presenca-digital",
    label: "Metricool",
    summary: "Agendamento, publicação e métricas sociais com configuração gerenciada.",
    state: "nao-configurado",
    priority: "essencial",
    capabilities: [
      { id: "publicar-conteudo", unlocked: false },
      { id: "programar-publicacao", unlocked: false },
      { id: "ler-metricas", unlocked: false },
    ],
    primaryPendency: "Autorizar a conta Metricool pelo MCP oficial.",
    impact: ["Sem o MCP Metricool autorizado, as capacidades sociais permanecem indisponíveis."],
    evidence: "produto",
    evidenceNote: "O MCP remoto oficial é o transporte principal; a API tradicional é um caminho avançado preservado.",
  },
  {
    id: "site",
    groupId: "presenca-digital",
    label: "Site",
    summary: "Domínio e catálogo público de imóveis.",
    state: "nao-configurado",
    priority: "essencial",
    capabilities: [
      { id: "identified", unlocked: false },
      { id: "publish", unlocked: false },
      { id: "metrics", unlocked: false },
    ],
    primaryPendency: "Conectar domínio e publicação do catálogo.",
    impact: ["O site ainda não está disponível como presença institucional validada."],
    evidence: "produto",
    evidenceNote: "Sem registro persistido de site nesta unidade.",
  },
  {
    id: "google-search-console",
    groupId: "presenca-digital",
    label: "Google Search Console",
    summary: "Leitura de indexação e termos de busca do site.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [{ id: "metrics", unlocked: false }],
    primaryPendency: "Conectar propriedade verificada do site.",
    impact: ["Dados de busca orgânica do site ainda não estão disponíveis."],
    evidence: "documentado",
    evidenceNote: "Sem registro persistido de Search Console nesta unidade.",
  },
  {
    id: "google-analytics",
    groupId: "presenca-digital",
    label: "Google Analytics",
    summary: "Leitura de tráfego e eventos do site.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [{ id: "metrics", unlocked: false }],
    primaryPendency: "Conectar GA4/GTM do site.",
    impact: ["Métricas de tráfego do site ainda não estão disponíveis."],
    evidence: "documentado",
    evidenceNote: "Sem registro persistido de GA4/GTM nesta unidade.",
  },
  {
    id: "google-business-profile",
    groupId: "presenca-digital",
    label: "Google Business Profile",
    summary: "Presença local da imobiliária no Google.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [
      { id: "identified", unlocked: false },
      { id: "publish", unlocked: false },
      { id: "metrics", unlocked: false },
    ],
    primaryPendency: "Conectar perfil verificado da imobiliária.",
    impact: ["Presença local no Google ainda não está disponível."],
    evidence: "documentado",
    evidenceNote: "Sem registro persistido de Google Business Profile nesta unidade.",
  },
  {
    id: "google-ads",
    groupId: "anuncios",
    label: "Google Ads",
    summary: "Capacidade futura de campanhas de busca.",
    state: "em-breve",
    priority: "futuro",
    capabilities: [{ id: "write", unlocked: false }],
    primaryPendency: null,
    impact: [],
    evidence: "planejado",
    evidenceNote: "Capacidade futura; não entra como falha operacional.",
  },
  {
    id: "base-marca",
    groupId: "producao-criativa",
    label: "Base de marca",
    summary: "Brand kit operacional da imobiliária.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [{ id: "produzir-criativos", unlocked: false }],
    primaryPendency: "Configurar brand kit real.",
    impact: ["Produção criativa ainda não tem base de marca validada."],
    evidence: "documentado",
    evidenceNote: "Não fica operacional até existir brand kit real.",
  },
  {
    id: "canva",
    groupId: "producao-criativa",
    label: "Canva",
    summary: "Designs, assets, templates e brand kits pela conexao MCP oficial do Canva.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [],
    primaryPendency: "Autorizar a conta Canva pelo MCP oficial.",
    impact: ["Sem o MCP Canva autorizado, os recursos criativos do provider permanecem indisponiveis."],
    evidence: "produto",
    evidenceNote: "Tools e capabilities sao descobertas no runtime apos a autorizacao; nenhuma capability de plano e presumida.",
  },
  {
    id: "templates",
    groupId: "producao-criativa",
    label: "Templates",
    summary: "Modelos aprovados para criativos e materiais comerciais.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [{ id: "produzir-criativos", unlocked: false }],
    primaryPendency: "Aprovar ao menos um template real.",
    impact: ["Produção criativa ainda não tem template aprovado."],
    evidence: "documentado",
    evidenceNote: "Não fica operacional até existir template aprovado.",
  },
  {
    id: "biblioteca-midias",
    groupId: "producao-criativa",
    label: "Biblioteca de mídias",
    summary: "Fotos, vídeos e materiais de entrada vinculados aos imóveis.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [{ id: "produzir-criativos", unlocked: false }],
    primaryPendency: "Vincular mídias reais aos imóveis.",
    impact: ["Produção criativa ainda não tem material de entrada."],
    evidence: "produto",
    evidenceNote: "Disponível somente quando houver mídia real vinculada aos imóveis.",
  },
  {
    id: "geracao-criativa",
    groupId: "producao-criativa",
    label: "Geração criativa",
    summary: "Geração de peças a partir de marca, templates e mídias.",
    state: "nao-configurado",
    priority: "importante",
    capabilities: [
      { id: "produzir-criativos", unlocked: false },
      { id: "gerar-narracao", unlocked: false },
    ],
    primaryPendency: "Concluir base de marca, templates e material de entrada.",
    impact: ["Geração criativa ainda não tem os pré-requisitos operacionais."],
    evidence: "documentado",
    evidenceNote: "Providers podem aparecer futuramente nos detalhes; consumo fica em Contas & Consumo.",
  },
];

export function connectionsByGroup(groupId: ConnectionEntry["groupId"]): ConnectionEntry[] {
  return CONNECTIONS_CATALOG.filter((entry) => entry.groupId === groupId);
}
