import type { GrowthCollection, GrowthCounter, GrowthStatusAccent } from "./types";

export const MOCK_GROWTH_COLLECTION_COUNTERS: GrowthCounter[] = [
  { label: "Assets", value: "38", detail: "por imóvel e coleção" },
  { label: "Packages", value: "9", detail: "pacotes aprovados" },
  { label: "Campanhas", value: "4", detail: "relacionadas ao acervo" },
  { label: "Reutilizações", value: "6", detail: "uso reaproveitado" },
  { label: "Collections", value: "3", detail: "patrimônio agrupado" },
];

export const GROWTH_COLLECTION_STATUS_ACCENT: GrowthStatusAccent = {
  Aprovado: "coldGreen",
  "Em uso": "cyan",
  Arquivado: "graphite",
  "Pronto para campanha": "lilac",
};

export const MOCK_GROWTH_COLLECTIONS: GrowthCollection[] = [
  {
    id: "property_altiplano_001",
    tenantId: "tenant_mock_growth_001",
    name: "Apartamento Altiplano",
    kind: "Property",
    status: "Pronto para campanha",
    subtitle: "Patrimônio pronto para reuso em campanhas de visita qualificada.",
    assets: [
      { label: "Fotos", value: "14", role: "primary" },
      { label: "Vídeos", value: "3", role: "cyan" },
      { label: "Planta", value: "1", role: "petrol" },
      { label: "Tour 360", value: "1", role: "lilac" },
      { label: "Documentos", value: "2", role: "neutral" },
    ],
    packages: ["Reel Premium", "Carrossel Alto Padrão", "Site Hero"],
    marketingAssets: ["Lançamento Premium", "Open House Julho"],
    campaigns: ["Instagram Feed", "Meta Leads", "Site Destaque"],
    knowledge: [
      { label: "Última aprovação", value: "Reel Premium aprovado sem ajuste" },
      { label: "Último pacote reutilizado", value: "Site Hero" },
      { label: "Créditos totais consumidos", value: "42" },
      { label: "Aprovações sem ajuste", value: "3" },
      { label: "Itens arquivados", value: "1" },
      { label: "Itens reutilizados", value: "4" },
    ],
    reusableReason: "O imóvel tem fotos, vídeo curto, planta e pacote aprovado com argumento consistente.",
    campaignOpportunity: "Reutilizar o pacote premium em Meta Leads com chamada de visita.",
    palette: ["primary", "lilac"],
    items: [
      {
        id: "altiplano_reel_premium",
        title: "Reel Premium",
        type: "Package",
        property: "Apartamento Altiplano",
        channel: "Instagram Reels",
        status: "Aprovado",
        credits: "18",
        reuses: "2",
        lastCampaign: "Instagram Feed",
        headline: "Vista alta, rotina leve",
        supportingText: "Pacote aprovado para destacar varanda, metragem e diferenciais.",
        palette: ["primary", "lilac"],
      },
      {
        id: "altiplano_open_house_julho",
        title: "Open House Julho",
        type: "Marketing Asset",
        property: "Apartamento Altiplano",
        channel: "Meta Leads",
        status: "Pronto para campanha",
        credits: "10",
        reuses: "1",
        lastCampaign: "Meta Leads",
        headline: "Visita qualificada",
        supportingText: "Asset de campanha com convite para agenda presencial.",
        palette: ["cyan", "petrol"],
      },
    ],
  },
  {
    id: "property_cabo_branco_014",
    tenantId: "tenant_mock_growth_001",
    name: "Cobertura Cabo Branco",
    kind: "Property",
    status: "Em uso",
    subtitle: "Acervo de alto padrão com foco em vista, área social e acabamento.",
    assets: [
      { label: "Fotos", value: "11", role: "primary" },
      { label: "Vídeos", value: "2", role: "cyan" },
      { label: "Planta", value: "1", role: "petrol" },
      { label: "Tour 360", value: "0", role: "neutral" },
      { label: "Documentos", value: "1", role: "neutral" },
    ],
    packages: ["Carrossel Alto Padrão", "Meta Feed"],
    marketingAssets: ["Lançamento Premium"],
    campaigns: ["Instagram Feed", "Site Destaque"],
    knowledge: [
      { label: "Última aprovação", value: "Carrossel aprovado com ajuste de chamada" },
      { label: "Último pacote reutilizado", value: "Carrossel Alto Padrão" },
      { label: "Créditos totais consumidos", value: "28" },
      { label: "Aprovações sem ajuste", value: "1" },
      { label: "Itens arquivados", value: "0" },
      { label: "Itens reutilizados", value: "2" },
    ],
    reusableReason: "O pacote tem imagens fortes, canal definido e histórico recente de aprovação.",
    campaignOpportunity: "Reaproveitar o carrossel para Site Destaque com foco na área gourmet.",
    palette: ["petrol", "primary"],
    items: [
      {
        id: "cabo_branco_carrossel",
        title: "Carrossel Alto Padrão",
        type: "Package",
        property: "Cobertura Cabo Branco",
        channel: "Instagram Feed",
        status: "Em uso",
        credits: "12",
        reuses: "2",
        lastCampaign: "Site Destaque",
        headline: "Cobertura com presença",
        supportingText: "Pacote editorial para destacar vista, planta e área social.",
        palette: ["petrol", "primary"],
      },
    ],
  },
  {
    id: "property_manaira_009",
    tenantId: "tenant_mock_growth_001",
    name: "Manaíra Residence",
    kind: "Property",
    status: "Aprovado",
    subtitle: "Biblioteca enxuta para campanhas de visita e atendimento rápido.",
    assets: [
      { label: "Fotos", value: "7", role: "primary" },
      { label: "Vídeos", value: "1", role: "cyan" },
      { label: "Planta", value: "1", role: "petrol" },
      { label: "Tour 360", value: "0", role: "neutral" },
      { label: "Documentos", value: "1", role: "neutral" },
    ],
    packages: ["Story Visita"],
    marketingAssets: ["Open House Julho"],
    campaigns: ["Instagram Feed"],
    knowledge: [
      { label: "Última aprovação", value: "Story aprovado sem ajuste" },
      { label: "Último pacote reutilizado", value: "Story Visita" },
      { label: "Créditos totais consumidos", value: "14" },
      { label: "Aprovações sem ajuste", value: "2" },
      { label: "Itens arquivados", value: "0" },
      { label: "Itens reutilizados", value: "1" },
    ],
    reusableReason: "A biblioteca já liga localização, chamada de visita e perfil familiar.",
    campaignOpportunity: "Reusar o story em atendimento de fim de semana.",
    palette: ["ice", "cyan"],
    items: [
      {
        id: "manaira_story_visita",
        title: "Story Visita",
        type: "Package",
        property: "Manaíra Residence",
        channel: "Instagram Stories",
        status: "Aprovado",
        credits: "6",
        reuses: "1",
        lastCampaign: "Instagram Feed",
        headline: "Visita neste sábado",
        supportingText: "Pacote curto para captar interesse e levar ao atendimento.",
        palette: ["ice", "cyan"],
      },
    ],
  },
  {
    id: "property_jardim_oceania_004",
    tenantId: "tenant_mock_growth_001",
    name: "Jardim Oceania",
    kind: "Property",
    status: "Arquivado",
    subtitle: "Acervo parcialmente arquivado por falta de diferenciais claros.",
    assets: [
      { label: "Fotos", value: "4", role: "neutral" },
      { label: "Vídeos", value: "0", role: "neutral" },
      { label: "Planta", value: "0", role: "neutral" },
      { label: "Tour 360", value: "0", role: "neutral" },
      { label: "Documentos", value: "1", role: "neutral" },
    ],
    packages: ["Meta Feed"],
    marketingAssets: ["Captação Proprietário"],
    campaigns: ["Meta Leads"],
    knowledge: [
      { label: "Última aprovação", value: "Sem aprovação final" },
      { label: "Último pacote reutilizado", value: "Nenhum" },
      { label: "Créditos totais consumidos", value: "0" },
      { label: "Aprovações sem ajuste", value: "0" },
      { label: "Itens arquivados", value: "2" },
      { label: "Itens reutilizados", value: "0" },
    ],
    reusableReason: "Há pouco patrimônio reaproveitável; faltam diferenciais do imóvel.",
    campaignOpportunity: "Revisar dados antes de enviar qualquer campanha.",
    palette: ["wine", "amber"],
    items: [
      {
        id: "jardim_oceania_meta_feed",
        title: "Meta Feed",
        type: "Package",
        property: "Jardim Oceania",
        channel: "Meta Feed",
        status: "Arquivado",
        credits: "0",
        reuses: "0",
        lastCampaign: "Nenhuma",
        headline: "Oferta em ajuste",
        supportingText: "Pacote arquivado até o imóvel ter diferenciais suficientes.",
        palette: ["wine", "amber"],
      },
    ],
  },
  {
    id: "collection_luxo_jp",
    tenantId: "tenant_mock_growth_001",
    name: "Collection: Luxo João Pessoa",
    kind: "Collection",
    status: "Pronto para campanha",
    subtitle: "Coleção de imóveis premium com pacotes aprovados para reuso.",
    assets: [
      { label: "Fotos", value: "22", role: "primary" },
      { label: "Vídeos", value: "5", role: "cyan" },
      { label: "Planta", value: "3", role: "petrol" },
      { label: "Tour 360", value: "1", role: "lilac" },
      { label: "Documentos", value: "4", role: "neutral" },
    ],
    packages: ["Reel Premium", "Carrossel Alto Padrão", "Site Hero"],
    marketingAssets: ["Lançamento Premium", "Captação Proprietário"],
    campaigns: ["Instagram Feed", "Meta Leads", "Site Destaque"],
    knowledge: [
      { label: "Última aprovação", value: "Coleção aprovada para campanha premium" },
      { label: "Último pacote reutilizado", value: "Reel Premium" },
      { label: "Créditos totais consumidos", value: "70" },
      { label: "Aprovações sem ajuste", value: "5" },
      { label: "Itens arquivados", value: "1" },
      { label: "Itens reutilizados", value: "6" },
    ],
    reusableReason: "A coleção agrupa imóveis com linguagem visual consistente e pacotes já aprovados.",
    campaignOpportunity: "Reutilizar o conjunto premium em campanha de captação qualificada.",
    palette: ["lilac", "primary"],
    items: [
      {
        id: "luxo_jp_lancamento_premium",
        title: "Lançamento Premium",
        type: "Marketing Asset",
        property: "Collection: Luxo João Pessoa",
        channel: "Meta Leads",
        status: "Pronto para campanha",
        credits: "16",
        reuses: "3",
        lastCampaign: "Meta Leads",
        headline: "Imóveis de presença",
        supportingText: "Asset aprovado para organizar imóveis premium por coleção.",
        palette: ["lilac", "primary"],
      },
    ],
  },
  {
    id: "collection_open_house_julho",
    tenantId: "tenant_mock_growth_001",
    name: "Collection: Open House Julho",
    kind: "Collection",
    status: "Em uso",
    subtitle: "Coleção operacional para visitas e redistribuição em canais ativos.",
    assets: [
      { label: "Fotos", value: "18", role: "primary" },
      { label: "Vídeos", value: "4", role: "cyan" },
      { label: "Planta", value: "2", role: "petrol" },
      { label: "Tour 360", value: "0", role: "neutral" },
      { label: "Documentos", value: "3", role: "neutral" },
    ],
    packages: ["Story Visita", "Meta Feed", "Site Hero"],
    marketingAssets: ["Open House Julho"],
    campaigns: ["Instagram Feed", "Meta Leads"],
    knowledge: [
      { label: "Última aprovação", value: "Open House aprovado para campanha" },
      { label: "Último pacote reutilizado", value: "Story Visita" },
      { label: "Créditos totais consumidos", value: "36" },
      { label: "Aprovações sem ajuste", value: "4" },
      { label: "Itens arquivados", value: "0" },
      { label: "Itens reutilizados", value: "5" },
    ],
    reusableReason: "A coleção tem assets e pacotes já usados em visita, com histórico de aprovação.",
    campaignOpportunity: "Reaproveitar assets de visita no canal de leads.",
    palette: ["cyan", "primary"],
    items: [
      {
        id: "open_house_julho_asset",
        title: "Open House Julho",
        type: "Marketing Asset",
        property: "Collection: Open House Julho",
        channel: "Instagram Feed",
        status: "Em uso",
        credits: "14",
        reuses: "5",
        lastCampaign: "Instagram Feed",
        headline: "Agenda de visitas",
        supportingText: "Asset de coleção para organizar imóveis com chamada de visita.",
        palette: ["cyan", "primary"],
      },
    ],
  },
];
